coverage:
  range: 70..100        # badge color scale
  round: down
  precision: 1

  status:
    project:
      default:
        target: 80%     # aim for at least 80% total coverage
        threshold: 1%   # allow PRs to drop max 1% vs base branch
        informational: true
    patch:
      default:
        target: 80%     # aim for at least 80% coverage on new code
        informational: true

ignore:
  - "tests/*"           # don’t measure test files themselves
  - "docs/*"            # ignore docs
  - "manage.py"

comment:
  layout: "diff, files, tree"   # what shows up in PR comments
  behavior: default             # update comment instead of posting new one each push
  require_changes: false        # always post comment, even if no coverage change
