blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/SamuelJennings/django-flex-menus/blob/main/README.md
    about: Check the documentation for usage examples and API reference
  - name: 💬 Discussions
    url: https://github.com/SamuelJennings/django-flex-menus/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🛡️ Security Issues
    url: https://github.com/SamuelJennings/django-flex-menus/security/advisories/new
    about: Report security vulnerabilities privately
